### ISSUE TITLE
Does not build in Linux =>3.16

### ISSUE THREAD

**Issue by mantheman** [lintweaker/mytekusb2#5]
CC [M]  sound/usb/mytek/chip.o
sound/usb/mytek/chip.c: In function 'mytek_chip_probe':
sound/usb/mytek/chip.c:125:2: error: implicit declaration of function 'snd_card_create' [-Werror=implicit-function-declaration]
cc1: some warnings being treated as errors
make[4]: *** [sound/usb/mytek/chip.o] Error 1
make[3]: *** [sound/usb/mytek] Error 2
make[2]: *** [sound/usb] Error 2
make[1]: *** [sound] Error 2
make[1]: Leaving directory `/root/linux-3.18-rc2'
make: *** [debian/stamp/build/kernel] Error 2
